<?php

namespace App\Plugins\User\Yuyucalendar\Services;

use Illuminate\Support\Facades\Crypt;

class CalendarReturnService
{
    public static function fromRequest($request, int $source_frame_id): ?string
    {
        return (new self())->resolve($request->input('ycal_return'), $source_frame_id);
    }

    public function append(string $detail_url, string $token): string
    {
        $parts = explode('#', $detail_url, 2);
        return $parts[0] . (strpos($parts[0], '?') === false ? '?' : '&') . 'ycal_return=' . rawurlencode($token)
            . (isset($parts[1]) ? '#' . $parts[1] : '');
    }

    /** Authenticated return context generated by YuyuCalendar, never an arbitrary request URL. */
    public function token(string $return_url, int $source_frame_id): string
    {
        return Crypt::encryptString(json_encode(['url' => $return_url, 'source_frame_id' => $source_frame_id]));
    }

    public function resolve($token, int $source_frame_id): ?string
    {
        if (!is_string($token) || $token === '' || strlen($token) > 16384) {
            return null;
        }
        try {
            $context = json_decode(Crypt::decryptString($token), true);
        } catch (\Illuminate\Contracts\Encryption\DecryptException $exception) {
            return null;
        }
        if (!is_array($context) || ($context['source_frame_id'] ?? null) !== $source_frame_id
            || !is_string($context['url'] ?? null)) {
            return null;
        }
        $target = parse_url($context['url']);
        $base = parse_url(url('/'));
        if (!$target || isset($target['user']) || isset($target['pass'])
            || ($target['scheme'] ?? '') !== ($base['scheme'] ?? '')
            || ($target['host'] ?? '') !== ($base['host'] ?? '')
            || ($target['port'] ?? null) !== ($base['port'] ?? null)) {
            return null;
        }
        $base_path = rtrim($base['path'] ?? '', '/');
        $path = $target['path'] ?? '';
        if ($base_path !== '' && $path !== $base_path && strpos($path, $base_path . '/') !== 0) {
            return null;
        }
        return $context['url'];
    }
}
